### ISSUE TITLE
Where is the official .proto file?

### ISSUE THREAD

**Issue by aeryaguzov** [openrtb/OpenRTB#5]
RTB protocol usually has its own official .proto file, For example google: https://developers.google.com/ad-exchange/rtb/downloads/realtime-bidding-proto.txt

There is one file attached to google code project(now unsupported) (https://code.google.com/p/openrtb/issues/attachmentText?id=14&aid=140008000&name=OpenRtb.proto&token=873ef9e3c79babbd442ff40906c26cd3) which is not official (a part of the issue).

So, where is OpenRTB official .proto file?

**Comment by samtingleff** [comment]
@aeryaguzov and others there is in fact an ongoing effort to put together standardized protobuf schemas for AdCOM/OpenRTB. This is in progress at https://github.com/InteractiveAdvertisingBureau/openrtb-proto-v2 for OpenRTB 2.X.
